/* //device/libs/telephony/ril_unsol_commands.h
**
** Copyright 2006, The Android Open Source Project
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
*/
    {SAMSUNG_UNSOL_RESPONSE_BASE, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_RELEASE_COMPLETE_MESSAGE, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_STK_SEND_SMS_RESULT, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_STK_CALL_CONTROL_RESULT, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_DUN_CALL_STATUS, NULL, WAKE_PARTIAL},
    // RIL_UNSOL_RESPONSE_LINE_SMS_COUNT - not used in stock RIL.java
    // RIL_UNSOL_RESPONSE_LINE_SMS_READ - not used in stock RIL.java
    {RIL_UNSOL_O2_HOME_ZONE_INFO, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_DEVICE_READY_NOTI, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_GPS_NOTI, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_AM, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_DUN_PIN_CONTROL_SIGNAL, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_DATA_SUSPEND_RESUME, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_SAP, NULL, WAKE_PARTIAL},
    // RIL_UNSOL_RESPONSE_NO_NETWORK_RESPONSE - not used in stock RIL.java
    // RIL_UNSOL_SIM_SMS_STORAGE_AVAILALE - not used in stock RIL.java
    {RIL_UNSOL_HSDPA_STATE_CHANGED, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_WB_AMR_STATE, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_TWO_MIC_STATE, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_DHA_STATE, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_UART, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_SIM_PB_READY, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_PCMCLOCK_STATE, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_1X_SMSPP, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_VE, NULL, WAKE_PARTIAL},
    // RIL_UNSOL_RINGBACK_TONE_STATE - not used in stock RIL.java
    // RIL_UNSOL_FACTORY_AM - not used in stock RIL.java
    {RIL_UNSOL_IMS_REGISTRATION_STATE_CHANGED, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_MODIFY_CALL, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_SRVCC_HANDOVER, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_CS_FALLBACK, NULL, WAKE_PARTIAL},
    // RIL_UNSOL_UICC_SUBSCRIPTION_STATUS_CHANGED already defined, see ril_unsol_commands.h
    {RIL_UNSOL_VOICE_SYSTEM_ID, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_SMARTAS_NOTI, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_IMS_RETRYOVER, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_STK_ALPHA_ID, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_PB_INIT_COMPLETE, NULL, WAKE_PARTIAL},
    // RIL_UNSOL_CP_POSITION - not used in stock RIL.java
    // RIL_UNSOL_RESPONSE_HANDOVER - not used in stock RIL.java
    // RIL_UNSOL_IPV6_ADDR - not used in stock RIL.java
    // RIL_UNSOL_NWK_INIT_DISC_REQUEST - not used in stock RIL.java
    {RIL_UNSOL_RTS_INDICATION, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_RILD_RESET_NOTI, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_HOME_NETWORK_NOTI, NULL, WAKE_PARTIAL},
    // RIL_UNSOL_CDMA_SIP_REG_NOTI - not used in stock RIL.java
    {RIL_UNSOL_OMADM_SEND_DATA, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_DUN, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_SYSTEM_REBOOT, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_VOICE_PRIVACY_CHANGED, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_UTS_GETSMSCOUNT, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_UTS_GETSMSMSG, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_UTS_GET_UNREAD_SMS_STATUS, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_MIP_CONNECT_STATUS, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_STK_CALL_STATUS, NULL, WAKE_PARTIAL},
